version: '3'

services:

  nginx:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: nginx
    networks:
    - envoymesh
    ports:
      - "8080:80"

  nginx-proxy:
    image: nginx
    networks:
    - envoymesh
    ports:
      - "8081:80"
    volumes:
      - ${PWD}/nginx-proxy.conf:/etc/nginx/conf.d/nginx-proxy.conf

  envoy:
    image: envoyproxy/envoy-alpine:v1.14.1
    networks:
    - envoymesh
    ports:
      - "9901:9901"
      - "10000:10000"
    volumes:
      - ${PWD}/etc-envoy:/etc/envoy

networks:
  envoymesh: {}
